In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
test_df = pd.read_csv("smsspam_test.csv",encoding='utf-8')
test_df.head()

000  10  100  1000  10p  11  12hrs  150  150p  150ppm  ...  xxx  ya  yeah  \
0    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
1    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
2    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
3    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
4    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   

   year  years  yes  yesterday  yo  yup  _label_  
0     0      0    0          0   0    0        0  
1     0      0    0          0   0    0        0  
2     0      0    0          0   0    0        0  
3     0      0    0          0   0    0        1  
4     0      0    0          0   0    0        0  

[5 rows x 501 columns]

In [3]:
train_df = pd.read_csv("smsspam_train.csv",encoding='utf-8')
train_df.head()

000  10  100  1000  10p  11  12hrs  150  150p  150ppm  ...  xxx  ya  yeah  \
0    0   0    0     0    0   0      0    0     0       0  ...    0   1     0   
1    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
2    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
3    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   
4    0   0    0     0    0   0      0    0     0       0  ...    0   0     0   

   year  years  yes  yesterday  yo  yup  _label_  
0     0      0    0          0   0    0        0  
1     0      0    0          0   0    0        0  
2     0      0    0          0   0    0        0  
3     0      0    0          0   0    0        0  
4     0      0    0          0   0    0        0  

[5 rows x 501 columns]

In [4]:
features = train_df.iloc[:,[0,499]].values

In [5]:
features

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [6]:
target = train_df.iloc[:,500].values
target

array([0, 0, 0, ..., 0, 1, 0])

In [7]:
classifier = BernoulliNB()

In [8]:
classifier.fit(features, target)

BernoulliNB()

In [9]:
features_test = test_df.iloc[:,[0,499]].values

In [10]:
target_test = test_df.iloc[:,500].values

In [44]:
unique, counts = np.unique(target_test, return_counts=True)
dict(zip(unique, counts))

{0: 1599, 1: 241}

In [11]:
y_pred = classifier.predict(features_test)

In [12]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
unique, counts = np.unique(y_pred, return_counts=True)
dict(zip(unique, counts))

{0: 1827, 1: 13}

In [13]:
with open('nb_predictions.txt', 'w', newline='') as file:
    for output in y_pred:
        file.write(str(output) + '\n')

In [14]:
model = LogisticRegression()

In [15]:
model.fit(features, target)

LogisticRegression()

In [16]:
lr_predict = model.predict(features_test)
lr_predict

array([0, 0, 0, ..., 0, 0, 0])

In [42]:
unique, counts = np.unique(lr_predict, return_counts=True)
dict(zip(unique, counts))

{0: 1827, 1: 13}

In [17]:
with open('lg_predictions.txt', 'w', newline='') as file:
    for output in lr_predict:
        file.write(str(output) + '\n')

In [18]:
def compute_score (test_score: np.array, predict_score: np.array)-> float:
    return sum(predict_score==test_score)/float(len(test_score))

In [19]:
#accuracy_score(target_test,y_pred)

In [20]:
#accuracy_score(target_test,lr_predict)

In [21]:
#accuracy = sum(lr_predict==target_test)/float(len(target_test))
#accuracy

In [22]:
#np.count_nonzero(lr_predict==target_test)

In [23]:
#len(target_test)

In [24]:
compute_score(target_test, y_pred)

0.8760869565217392

In [25]:
compute_score(target_test, lr_predict)

0.8760869565217392

In [26]:
dt_predictions = np.loadtxt("dt_predictions.txt",dtype = 'int64')
dt_predictions

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
unique, counts = np.unique(dt_predictions, return_counts=True)
dict(zip(unique, counts))

{0: 1594, 1: 246}

In [27]:
compute_score(target_test, dt_predictions)

0.970108695652174

In [28]:
combine = pd.DataFrame(y_pred, columns = ['Naive'])
combine.head(10)

Naive
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0

In [29]:
combine['LR_Predict'] = pd.DataFrame(y_pred)
combine.head(10)

Naive  LR_Predict
0      0           0
1      0           0
2      0           0
3      0           0
4      0           0
5      0           0
6      0           0
7      0           0
8      0           0
9      0           0

In [30]:
combine['Decision'] = pd.DataFrame(dt_predictions)
combine.head(10)

Naive  LR_Predict  Decision
0      0           0         0
1      0           0         0
2      0           0         0
3      0           0         0
4      0           0         0
5      0           0         0
6      0           0         1
7      0           0         0
8      0           0         0
9      0           0         0

In [31]:
np.count_nonzero(dt_predictions==target_test)

1785

In [52]:
combine['Final'] = combine['Naive'] + combine['LR_Predict'] + combine['Decision']

In [53]:
combine.head(10)

Naive  LR_Predict  Decision  Final
0      0           0         0      0
1      0           0         0      0
2      0           0         0      0
3      0           0         0      0
4      0           0         0      0
5      0           0         0      0
6      0           0         1      0
7      0           0         0      0
8      0           0         0      0
9      0           0         0      0

In [46]:
combine.loc[combine['Final'] == 0,'Final'] = 1

In [47]:
combine.loc[combine['Final'] == 1,'Final'] = 1

In [48]:
combine.loc[combine['Final'] == 2,'Final'] = 1

In [49]:
combine.loc[combine['Final'] == 3,'Final'] = 1
combine.head(10)

Naive  LR_Predict  Decision  Final
0      0           0         0      1
1      0           0         0      1
2      0           0         0      1
3      0           0         0      1
4      0           0         0      1
5      0           0         0      1
6      0           0         1      1
7      0           0         0      1
8      0           0         0      1
9      0           0         0      1

In [50]:
voted_prediction = combine['Final'].values

In [51]:
compute_score(target_test, voted_prediction)

0.1309782608695652